"""Official Unifiles Python SDK."""

from .client import AsyncUnifilesClient, UnifilesClient
from .exceptions import (
    AuthenticationError,
    ConflictError,
    NotFoundError,
    PermissionError,
    ProcessingError,
    RateLimitError,
    ServerError,
    TimeoutError,
    TransportError,
    UnifilesError,
    ValidationError,
)
from .models import (
    APIKey,
    AsyncExtractionJob,
    AsyncIndexedDocument,
    Chunk,
    DeletionResult,
    ExtractionJob,
    File,
    HealthDetails,
    HealthStatus,
    IndexedDocument,
    KnowledgeBase,
    ListResponse,
    SearchResults,
    SupportedFileTypes,
    UsageLimits,
    UsageStats,
    Webhook,
)

__version__ = "0.1.0"

__all__ = [
    "APIKey",
    "AsyncIndexedDocument",
    "AsyncExtractionJob",
    "AsyncUnifilesClient",
    "AuthenticationError",
    "Chunk",
    "ConflictError",
    "DeletionResult",
    "IndexedDocument",
    "ExtractionJob",
    "File",
    "HealthDetails",
    "HealthStatus",
    "KnowledgeBase",
    "ListResponse",
    "NotFoundError",
    "PermissionError",
    "ProcessingError",
    "RateLimitError",
    "SearchResults",
    "ServerError",
    "SupportedFileTypes",
    "TimeoutError",
    "TransportError",
    "UnifilesClient",
    "UnifilesError",
    "UsageLimits",
    "UsageStats",
    "ValidationError",
    "Webhook",
]
