"""Official Unifiles Python SDK."""

from .client import AsyncUnifilesClient, UnifilesClient
from .exceptions import (
    AuthenticationError,
    ConflictError,
    NotFoundError,
    PermissionError,
    ProcessingError,
    RateLimitError,
    ServerError,
    TimeoutError,
    TransportError,
    UnifilesError,
    ValidationError,
)
from .models import (
    APIKey,
    AsyncDocument,
    AsyncExtraction,
    Chunk,
    DeletionResult,
    Document,
    Extraction,
    File,
    KnowledgeBase,
    ListResponse,
    SearchResults,
    SupportedFileTypes,
    UsageLimits,
    UsageStats,
    Webhook,
)

__version__ = "0.1.0"

__all__ = [
    "APIKey",
    "AsyncDocument",
    "AsyncExtraction",
    "AsyncUnifilesClient",
    "AuthenticationError",
    "Chunk",
    "ConflictError",
    "DeletionResult",
    "Document",
    "Extraction",
    "File",
    "KnowledgeBase",
    "ListResponse",
    "NotFoundError",
    "PermissionError",
    "ProcessingError",
    "RateLimitError",
    "SearchResults",
    "ServerError",
    "SupportedFileTypes",
    "TimeoutError",
    "TransportError",
    "UnifilesClient",
    "UnifilesError",
    "UsageLimits",
    "UsageStats",
    "ValidationError",
    "Webhook",
]
