# 大模型和嵌入模型的配置文件
api:
  language_embedding:
    - name: "Pro/BAAI/bge-m3"
      url: "https://api.siliconflow.cn/v1/embeddings"
      key: "sk-sqichvhplvkasryatqtmufwevhgnvcxzgqilurqxvvvllmpo"
      alias: "bge-m3"
# server组件
server_components:
  pg_vector:
    host: "192.168.132.149"
    port: "5437"
    user: "postgres"
    password: "postgres"
    database: "postgres"
    active: true
  minio:
    host: "192.168.132.149"
    port: "9000"
    access_key: "[REDACTED]"
    secret_key: "[REDACTED]"
    bucket_name: "publicfiles"
    region: "us-east-1"
    use_public_url: true
    public_url_prefix: "http://1.tcp.cpolar.cn:21729"
    active: true
  mineru:
    - url: "http://192.168.132.149:8889"
      active: true
  convert_format_server:
    - url: "http://192.168.132.149:8889"
      active: true