# 大模型和嵌入模型的配置文件
api:
  language_embedding:
    # - name: "Pro/BAAI/bge-m3"
    #   url: "https://api.siliconflow.cn/v1/embeddings"
    #   key: "sk-sqichvhplvkasryatqtmufwevhgnvcxzgqilurqxvvvllmpo"
    #   alias: "bge-m3"
    - name: "bge-m3-0"
      url: "http://127.0.0.1:9030/v1/embeddings"
      key: ""
      alias: "bge-m3"
    - name: "bge-m3-1"
      url: "http://127.0.0.1:9030/v1/embeddings"
      key: ""
      alias: "bge-m3"
    - name: "bge-m3-2"
      url: "http://127.0.0.1:9030/v1/embeddings"
      key: ""
      alias: "bge-m3"
    - name: "bge-m3-3"
      url: "http://127.0.0.1:9030/v1/embeddings"
      key: ""
      alias: "bge-m3"
    - name: "bge-m3-4"
      url: "http://127.0.0.1:9030/v1/embeddings"
      key: ""
      alias: "bge-m3"
    - name: "bge-m3-5"
      url: "http://127.0.0.1:9030/v1/embeddings"
      key: ""
      alias: "bge-m3"
    - name: "bge-m3-6"
      url: "http://127.0.0.1:9030/v1/embeddings"
      key: ""
      alias: "bge-m3"
    - name: "bge-m3-7"
      url: "http://127.0.0.1:9030/v1/embeddings"
      key: ""
      alias: "bge-m3"
  multimodal_llm:
    - name: "Qwen/Qwen2.5-VL-32B-Instruct"
      url: "https://api.siliconflow.cn/v1/chat/completions"
      key: "sk-sqichvhplvkasryatqtmufwevhgnvcxzgqilurqxvvvllmpo"
      alias: "Qwen2.5-VL-32B-Instruct"
  language_llm:
    - name: "Qwen/Qwen3-8B"
      url: "https://api.siliconflow.cn/v1/chat/completions"
      key: "sk-sqichvhplvkasryatqtmufwevhgnvcxzgqilurqxvvvllmpo"
      alias: "Qwen/Qwen3-8B"
# server组件
server_components:
  pg_vector:
    host: "192.168.132.149"
    port: "5437"
    user: "postgres"
    password: "postgres"
    database: "postgres"
    active: true
  minio:
    host: "192.168.132.149"
    port: 9000
    access_key: "[REDACTED]"
    secret_key: "[REDACTED]"
    bucket_name: "publicfiles"
    region: "us-east-1"
    use_public_url: true
    public_url_prefix: "https://149min9000.cpolar.cn"
    active: true
  mineru:
    - url: "http://127.0.0.1:8889"
      active: true
  convert_format_server:
    - url: "http://192.168.132.149:7758"
      active: true

text_chunk_strategy:
  SlidingWindow:
    module: "normal"
    chunk_size: 800
    chunk_overlap: 128

graph_module:
  summary_strategy:
    window_size: 8000

embedding_settings:
  semaphore: 8