#!/usr/bin/env python3
"""
Simple test script for the upload_minio endpoint
Tests the file upload functionality on port 8000
"""

import requests
import json
from pathlib import Path
import io

# Server configuration
SERVER_URL = "http://localhost:8000"
UPLOAD_ENDPOINT = f"{SERVER_URL}/upload_minio"
HEALTH_ENDPOINT = f"{SERVER_URL}/health"

def test_health_check():
    """Test if the server is running"""
    print("🔍 Testing server health...")
    try:
        response = requests.get(HEALTH_ENDPOINT, timeout=5)
        if response.status_code == 200:
            print("✅ Server is running and healthy")
            return True
        else:
            print(f"❌ Server health check failed: {response.status_code}")
            return False
    except requests.exceptions.RequestException as e:
        print(f"❌ Cannot connect to server: {e}")
        return False

def create_test_file():
    """Create a simple test file for upload"""
    test_content = b"This is a test file for upload_minio endpoint testing.\nGenerated by test.py script."
    return test_content, "test_file.txt"

def test_upload_with_user_id(user_id="test_user"):
    """Test file upload with specific user_id"""
    print(f"\n📤 Testing upload with user_id: {user_id}")

    # Create test file
    file_content, filename = create_test_file()

    # Prepare form data
    files = {
        'upload_file': (filename, io.BytesIO(file_content), 'text/plain')
    }
    data = {
        'user_id': user_id
    }

    try:
        response = requests.post(UPLOAD_ENDPOINT, files=files, data=data, timeout=30)

        print(f"Status Code: {response.status_code}")
        print(f"Response: {json.dumps(response.json(), indent=2)}")

        if response.status_code == 200:
            result = response.json()
            if result.get("status") == "success":
                print("✅ Upload successful!")
                data = result.get("data", {})
                print(f"   File ID: {data.get('file_id')}")
                print(f"   Public URL: {data.get('public_url')}")
                print(f"   File Size: {data.get('file_size')} bytes")
                return True
            else:
                print(f"❌ Upload failed: {result.get('message')}")
                return False
        else:
            print(f"❌ Upload failed with status code: {response.status_code}")
            return False

    except requests.exceptions.RequestException as e:
        print(f"❌ Request failed: {e}")
        return False

def test_upload_without_user_id():
    """Test file upload without user_id (should use 'default')"""
    print(f"\n📤 Testing upload without user_id (should default to 'default')")

    # Create test file
    file_content, filename = create_test_file()

    # Prepare form data without user_id
    files = {
        'upload_file': (filename, io.BytesIO(file_content), 'text/plain')
    }

    try:
        response = requests.post(UPLOAD_ENDPOINT, files=files, timeout=30)

        print(f"Status Code: {response.status_code}")
        print(f"Response: {json.dumps(response.json(), indent=2)}")

        if response.status_code == 200:
            result = response.json()
            if result.get("status") == "success":
                print("✅ Upload successful!")
                return True
            else:
                print(f"❌ Upload failed: {result.get('message')}")
                return False
        else:
            print(f"❌ Upload failed with status code: {response.status_code}")
            return False

    except requests.exceptions.RequestException as e:
        print(f"❌ Request failed: {e}")
        return False

def test_upload_no_file():
    """Test upload without file (should fail)"""
    print(f"\n📤 Testing upload without file (should fail)")

    data = {
        'user_id': 'test_user'
    }

    try:
        response = requests.post(UPLOAD_ENDPOINT, data=data, timeout=30)

        print(f"Status Code: {response.status_code}")
        print(f"Response: {json.dumps(response.json(), indent=2)}")

        if response.status_code == 400:
            print("✅ Correctly rejected upload without file")
            return True
        else:
            print(f"❌ Expected 400 status code, got: {response.status_code}")
            return False

    except requests.exceptions.RequestException as e:
        print(f"❌ Request failed: {e}")
        return False

def test_upload_existing_file():
    """Test upload with an existing file if available"""
    print(f"\n📤 Testing upload with existing PDF file")

    # Try to find an existing file
    test_files = [
        "2024110410_wangyu (1).pdf",
        "README.md",
        "config.yaml",
        "main.py"
    ]

    for file_path in test_files:
        if Path(file_path).exists():
            print(f"Found existing file: {file_path}")

            with open(file_path, 'rb') as f:
                file_content = f.read()

            files = {
                'upload_file': (Path(file_path).name, io.BytesIO(file_content), 'application/octet-stream')
            }
            data = {
                'user_id': 'test_user_real_file'
            }

            try:
                response = requests.post(UPLOAD_ENDPOINT, files=files, data=data, timeout=30)

                print(f"Status Code: {response.status_code}")
                print(f"Response: {json.dumps(response.json(), indent=2)}")

                if response.status_code == 200:
                    result = response.json()
                    if result.get("status") == "success":
                        print("✅ Real file upload successful!")
                        return True
                    else:
                        print(f"❌ Upload failed: {result.get('message')}")
                        return False
                else:
                    print(f"❌ Upload failed with status code: {response.status_code}")
                    return False

            except requests.exceptions.RequestException as e:
                print(f"❌ Request failed: {e}")
                return False

    print("No existing files found for testing")
    return True

def main():
    """Run all tests"""
    print("🚀 Starting upload_minio endpoint tests")
    print("=" * 50)

    # Test server health first
    if not test_health_check():
        print("\n❌ Server is not running. Please start the server first:")
        print("   python main.py")
        return

    # Run all tests
    tests = [
        test_upload_with_user_id,
        test_upload_without_user_id,
        test_upload_no_file,
        test_upload_existing_file
    ]

    passed = 0
    total = len(tests)

    for test_func in tests:
        try:
            if test_func():
                passed += 1
        except Exception as e:
            print(f"❌ Test {test_func.__name__} failed with exception: {e}")

    print("\n" + "=" * 50)
    print(f"📊 Test Results: {passed}/{total} tests passed")

    if passed == total:
        print("🎉 All tests passed!")
    else:
        print("⚠️  Some tests failed. Check the output above for details.")

if __name__ == "__main__":
    main()
