site_name: Unifiles
site_url: https://unifiles.pages.dev
repo_url: https://github.com/ppppangu/Unifiles-doc
repo_name: ppppangu/Unifiles-doc
site_dir: site

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Features: Features/features.md
  - Learn: Learn/learn.md
  - Unifiles People: UnifilesPeople/unifiles_people.md
  - About: About/about.md
  - Release Notes: Release/release_note.md

theme:
  name: material
  lang: zh
  features:
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.footnote.tooltips
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes

plugins:
  - search
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true
        - locale: en
          name: English
          build: true
  - git-revision-date-localized:
      enable_creation_date: true

extra:
  version:
    provider: mike
