[project]
name = "unifiles-doc"
version = "0.1.0"
description = "Unifiles Documentation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs-git-committers-plugin-2>=2.5.0",
    "mkdocs-git-revision-date-localized-plugin>=1.4.7",
    "mkdocs-material>=9.6.20",
    "mkdocs-minify-plugin>=0.8.0",
    "mkdocs-static-i18n>=1.2.0",
]
