# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    confloat,
    conint,
    constr,
)


class APIKeyCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1, max_length=200) = Field(..., title='Name')
    scopes: list[str] | None = Field(None, title='Scopes')
    expires_at: AwareDatetime | None = Field(None, title='Expires At')


class APIKeyResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    key: str | None = Field(None, title='Key')
    key_prefix: str = Field(..., title='Key Prefix')
    scopes: list[str] = Field(..., title='Scopes')
    last_used_at: AwareDatetime | None = Field(None, title='Last Used At')
    expires_at: AwareDatetime | None = Field(None, title='Expires At')
    created_at: AwareDatetime = Field(..., title='Created At')


class BodyUploadFileV1FilesPost(BaseModel):
    file: bytes = Field(..., title='File')
    metadata: str | None = Field('{}', title='Metadata')
    tags: str | None = Field('[]', title='Tags')


class ChunkResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    document_id: str = Field(..., title='Document Id')
    document_title: str | None = Field(None, title='Document Title')
    content: str = Field(..., title='Content')
    score: float = Field(..., title='Score')
    vector_score: float | None = Field(None, title='Vector Score')
    keyword_score: float | None = Field(None, title='Keyword Score')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')


class DeletionResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    deleted: bool | None = Field(True, title='Deleted')


class DocumentCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    file_id: str = Field(..., title='File Id')
    title: str | None = Field(None, title='Title')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')


class Status(StrEnum):
    pending = 'pending'
    indexing = 'indexing'
    indexed = 'indexed'
    failed = 'failed'
    cancelled = 'cancelled'


class DocumentResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    kb_id: str = Field(..., title='Kb Id')
    file_id: str = Field(..., title='File Id')
    title: str | None = Field(None, title='Title')
    status: Status = Field(..., title='Status')
    chunk_count: int = Field(..., title='Chunk Count')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    error: dict[str, Any] | None = Field(None, title='Error')
    created_at: AwareDatetime = Field(..., title='Created At')
    indexed_at: AwareDatetime | None = Field(None, title='Indexed At')


class ErrorDetail(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: str = Field(..., title='Code')
    message: str = Field(..., title='Message')
    details: dict[str, Any] | None = Field(None, title='Details')
    request_id: str = Field(..., title='Request Id')


class ErrorEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: Literal[False] = Field(False, title='Success')
    error: ErrorDetail


class Mode(StrEnum):
    simple = 'simple'
    normal = 'normal'
    advanced = 'advanced'


class ExtractionCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    file_id: str = Field(..., title='File Id')
    mode: Mode | None = Field('normal', title='Mode')
    options: dict[str, Any] | None = Field(None, title='Options')


class Status1(StrEnum):
    pending = 'pending'
    processing = 'processing'
    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'


class ExtractionResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    file_id: str = Field(..., title='File Id')
    status: Status1 = Field(..., title='Status')
    mode: str = Field(..., title='Mode')
    progress: int | None = Field(None, title='Progress')
    markdown: str | None = Field(None, title='Markdown')
    total_pages: int | None = Field(None, title='Total Pages')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    error: dict[str, Any] | None = Field(None, title='Error')
    created_at: AwareDatetime = Field(..., title='Created At')
    completed_at: AwareDatetime | None = Field(None, title='Completed At')


class FileResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    filename: str = Field(..., title='Filename')
    content_type: str = Field(..., title='Content Type')
    size: int = Field(..., title='Size')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    tags: list[str] | None = Field(None, title='Tags')
    created_at: AwareDatetime = Field(..., title='Created At')
    updated_at: AwareDatetime | None = Field(None, title='Updated At')


class HybridSearchRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query: constr(min_length=1) = Field(..., title='Query')
    vector_weight: confloat(ge=0.0) | None = Field(0.7, title='Vector Weight')
    keyword_weight: confloat(ge=0.0) | None = Field(0.3, title='Keyword Weight')
    top_k: conint(ge=1, le=100) | None = Field(5, title='Top K')


class KnowledgeBaseCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1, max_length=200) = Field(..., title='Name')
    description: str | None = Field(None, title='Description')
    chunking_strategy: dict[str, Any] | None = Field(None, title='Chunking Strategy')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')


class KnowledgeBaseResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    description: str | None = Field(None, title='Description')
    chunking_strategy: dict[str, Any] = Field(..., title='Chunking Strategy')
    document_count: int = Field(..., title='Document Count')
    chunk_count: int = Field(..., title='Chunk Count')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    created_at: AwareDatetime = Field(..., title='Created At')
    updated_at: AwareDatetime | None = Field(None, title='Updated At')


class KnowledgeBaseUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1, max_length=200) | None = Field(None, title='Name')
    description: str | None = Field(None, title='Description')
    chunking_strategy: dict[str, Any] | None = Field(None, title='Chunking Strategy')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')


class ListDataAPIKeyResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[APIKeyResource] = Field(..., title='Items')
    total: int = Field(..., title='Total')
    limit: int = Field(..., title='Limit')
    offset: int = Field(..., title='Offset')
    has_more: bool = Field(..., title='Has More')


class ListDataDocumentResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[DocumentResource] = Field(..., title='Items')
    total: int = Field(..., title='Total')
    limit: int = Field(..., title='Limit')
    offset: int = Field(..., title='Offset')
    has_more: bool = Field(..., title='Has More')


class ListDataExtractionResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[ExtractionResource] = Field(..., title='Items')
    total: int = Field(..., title='Total')
    limit: int = Field(..., title='Limit')
    offset: int = Field(..., title='Offset')
    has_more: bool = Field(..., title='Has More')


class ListDataFileResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[FileResource] = Field(..., title='Items')
    total: int = Field(..., title='Total')
    limit: int = Field(..., title='Limit')
    offset: int = Field(..., title='Offset')
    has_more: bool = Field(..., title='Has More')


class ListDataKnowledgeBaseResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[KnowledgeBaseResource] = Field(..., title='Items')
    total: int = Field(..., title='Total')
    limit: int = Field(..., title='Limit')
    offset: int = Field(..., title='Offset')
    has_more: bool = Field(..., title='Has More')


class SearchRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query: constr(min_length=1) = Field(..., title='Query')
    top_k: conint(ge=1, le=100) | None = Field(5, title='Top K')
    threshold: confloat(ge=0.0, le=1.0) | None = Field(0, title='Threshold')
    filter: dict[str, Any] | None = Field(None, title='Filter')


class SearchResults(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query: str = Field(..., title='Query')
    chunks: list[ChunkResource] = Field(..., title='Chunks')
    total: int = Field(..., title='Total')


class SuccessEnvelopeAPIKeyResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: Literal[True] = Field(True, title='Success')
    data: APIKeyResource


class SuccessEnvelopeDeletionResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: Literal[True] = Field(True, title='Success')
    data: DeletionResult


class SuccessEnvelopeDocumentResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: Literal[True] = Field(True, title='Success')
    data: DocumentResource


class SuccessEnvelopeExtractionResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: Literal[True] = Field(True, title='Success')
    data: ExtractionResource


class SuccessEnvelopeFileResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: Literal[True] = Field(True, title='Success')
    data: FileResource


class SuccessEnvelopeKnowledgeBaseResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: Literal[True] = Field(True, title='Success')
    data: KnowledgeBaseResource


class SuccessEnvelopeListDataAPIKeyResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: Literal[True] = Field(True, title='Success')
    data: ListDataAPIKeyResource


class SuccessEnvelopeListDataDocumentResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: Literal[True] = Field(True, title='Success')
    data: ListDataDocumentResource


class SuccessEnvelopeListDataExtractionResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: Literal[True] = Field(True, title='Success')
    data: ListDataExtractionResource


class SuccessEnvelopeListDataFileResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: Literal[True] = Field(True, title='Success')
    data: ListDataFileResource


class SuccessEnvelopeListDataKnowledgeBaseResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: Literal[True] = Field(True, title='Success')
    data: ListDataKnowledgeBaseResource


class SuccessEnvelopeSearchResults(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: Literal[True] = Field(True, title='Success')
    data: SearchResults


class SuccessEnvelopeDictStrAny(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: Literal[True] = Field(True, title='Success')
    data: dict[str, Any] = Field(..., title='Data')


class SupportedFileTypes(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    document_types: list[str] = Field(..., title='Document Types')
    image_types: list[str] = Field(..., title='Image Types')
    all_types: list[str] = Field(..., title='All Types')


class WebhookCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: AnyUrl = Field(..., title='Url')
    events: list[str] = Field(..., min_length=1, title='Events')
    description: str | None = Field(None, title='Description')


class WebhookResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    url: str = Field(..., title='Url')
    events: list[str] = Field(..., title='Events')
    enabled: bool = Field(..., title='Enabled')
    description: str | None = Field(None, title='Description')
    last_delivery_at: AwareDatetime | None = Field(None, title='Last Delivery At')
    created_at: AwareDatetime = Field(..., title='Created At')
    updated_at: AwareDatetime | None = Field(None, title='Updated At')


class WebhookUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: AnyUrl | None = Field(None, title='Url')
    events: list[str] | None = Field(None, title='Events')
    enabled: bool | None = Field(None, title='Enabled')
    description: str | None = Field(None, title='Description')


class ListDataWebhookResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[WebhookResource] = Field(..., title='Items')
    total: int = Field(..., title='Total')
    limit: int = Field(..., title='Limit')
    offset: int = Field(..., title='Offset')
    has_more: bool = Field(..., title='Has More')


class SuccessEnvelopeListDataWebhookResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: Literal[True] = Field(True, title='Success')
    data: ListDataWebhookResource


class SuccessEnvelopeSupportedFileTypes(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: Literal[True] = Field(True, title='Success')
    data: SupportedFileTypes


class SuccessEnvelopeWebhookResource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: Literal[True] = Field(True, title='Success')
    data: WebhookResource
